name: Update Github Pages
on:
  push:
    branches:
      - master
jobs:
  update_pages:
    runs-on: ubuntu-latest
    outputs:
      cv_pdf_exists: ${{ steps.cv_pdf_exists.outputs.files_exists }}
      cv_changed: ${{ steps.cv_has_changes.outputs.cv }}
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: gh-pages
      - name: Update gh-pages branch
        run: |
          git config --global user.email "hushaohan@gmail.com"
          git config --global user.name "Shaohan Hu"
          git pull origin master --rebase
          git push -f
      - name: Check if gh-pages root has a cv.pdf
        id: cv_pdf_exists
        uses: andstor/file-existence-action@v1
        with:
          files: "./cv.pdf"
      - name: Check cv directory for changes
        uses: dorny/paths-filter@v2
        id: cv_has_changes
        with:
          filters: |
            cv:
              - 'cv/**'
  build_cv:
    needs: update_pages
    if: needs.update_pages.outputs.cv_pdf_exists == 'false' || needs.update_pages.outputs.cv_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Compile cv
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: cv/
          root_file: cv.tex
      - name: Check cv.pdf
        run: |
          file cv/cv.pdf | grep -q ' PDF '
      - name: Update cv.pdf
        run: |
          git config --global user.email "hushaohan@gmail.com"
          git config --global user.name "Shaohan Hu"
          git add cv/cv.pdf
          git mv -f cv/cv.pdf ./
          git commit -m "deploy cv.pdf"
          git push
